[project]
enable_telemetry = true
user_env = []
session_timeout = 3600
cache = false
allow_origins = ["*"]

# Add logo paths here
logo_light = "/public/logo_light.png"
logo_dark = "/public/logo_dark.png"

[authentication]
# Enable password authentication
require_login = true
# Enable OAuth callback handler for MS Entra ID
oauth_callback_handler = true

[features]
unsafe_allow_html = false
latex = false
auto_tag_thread = true

[features.spontaneous_file_upload]
enabled = true
accept = ["*/*"]
max_files = 20
max_size_mb = 500

[features.audio]
min_decibels = -45
initial_silence_timeout = 3000
silence_timeout = 1500
max_duration = 15000
chunk_duration = 1000
sample_rate = 44100

edit_message = true

[UI]
name = "AIDW Assistant"
default_collapse_content = true
cot = "full"

[UI.theme]
default = "dark"

[UI.theme.light]
background = "#FAFAFA"
paper = "#FFFFFF"

[UI.theme.light.primary]
main = "#007FFF"
dark = "#0059B2"
light = "#E6F0FF"

[UI.theme.light.text]
primary = "#212121"
secondary = "#616161"

[UI.theme.dark]
background = "#0A1929"
paper = "#0A1929"

[UI.theme.dark.primary]
main = "#007FFF"
dark = "#0059B2"
light = "#E6F0FF"

[UI.theme.dark.text]
primary = "#FFFFFF"
secondary = "#B2BAC2"

[code_block]
max_height = 500
theme = "github-dark"
copy_button = true
language = "python"

[meta]
generated_by = "1.1.402"